# Generated by Django 5.0.6 on 2024-06-16 16:21

import security.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='initial_recipient_secret',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='initial_sender_secret',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(default=security.models.Channel.create_random_name, max_length=100),
        ),
    ]
